const exercices = [
  {
    id: 0,
    class: "select-title",
    name: "Tous (défaut)",
    value: "title",
  },
  {
    id: 1,
    class: "select-title",
    name: "Musculation - Haut du corps",
    value: "title",
  },
  {
    id: 2,
    class: "select-item",
    name: "Developpé couché",
    value: "Developpé couché",
  },

  {
    id: 4,
    class: "select-item",
    name: "Rowing",
    value: "Rowing ",
  },
  {
    id: 5,
    class: "select-item",
    name: "Tirage Horizontal",
    value: "Tirage Horizontal",
  },
  {
    id: 6,
    class: "select-item",
    name: "Tirage Vertical",
    value: "Tirage Vertical",
  },
  {
    id: 9,
    class: "select-item",
    name: "Curl",
    value: "Curl",
  },
  {
    id: 10,
    class: "select-item",
    name: "Barre au front",
    value: "Barre au front",
  },
  {
    id: 11,
    class: "select-title",
    name: "Musculation - Bas du corps",
    value: "title",
  },
  {
    id: 3,
    class: "select-item",
    name: "Squat",
    value: "Squat",
  },
  {
    id: 7,
    class: "select-item",
    name: "Soulevé de terre",
    value: "Soulevé de terre",
  },
  {
    id: 12,
    class: "select-title",
    name: "Streetlifting - Haut du corps",
    value: "title",
  },
  {
    id: 8,
    class: "select-item",
    name: "Traction",
    value: "Traction",
  },
  {
    id: 13,
    class: "select-item",
    name: "Dips",
    value: "Dips",
  },
  {
    id: 14,
    class: "select-item",
    name: "Muscle Up",
    value: "Muscle Up",
  },
  {
    id: 19,
    class: "select-title",
    name: "Streetlifting - Bas du corps",
    value: "title",
  },
  {
    id: 20,
    class: "select-item",
    name: "Pistol Squat",
    value: "Pistol Squat",
  },
  {
    id: 21,
    class: "select-item",
    name: "Matrix Squat",
    value: "Matrix Squat",
  },
  {
    id: 22,
    class: "select-item",
    name: "Nordic Curl",
    value: "Nordic Curl",
  },
  {
    id: 23,
    class: "select-item",
    name: "Natural Leg Extension",
    value: "Natural Leg Extension",
  },
  {
    id: 15,
    class: "select-title",
    name: "Statique / Figures",
    value: "title",
  },
  {
    id: 16,
    class: "select-item",
    name: "Front Lever",
    value: "Front Lever",
  },
  {
    id: 17,
    class: "select-item",
    name: "Back Lever",
    value: "Back Lever",
  },
  {
    id: 18,
    class: "select-item",
    name: "Planche",
    value: "Planche",
  },
  {
    id: 24,
    class: "select-item",
    name: "Handstand / Poirier",
    value: "Handstand",
  },
  {
    id: 25,
    class: "select-item",
    name: "Maltsese",
    value: "Maltese",
  },
  {
    id: 26,
    class: "select-item",
    name: "Drapeau / Human Flag",
    value: "Drapeau",
  },
  {
    id: 27,
    class: "select-item",
    name: "Iron Cross / Croix de fer",
    value: "Iron Cross",
  },
  {
    id: 999,
    class: "select-item-own",
    name: "Entre ton propre exercice ici...",
    value: "own-exercice",
  },
];

export default exercices;
