const variantes = [
  {
    id: 0,
    class: "select-title",
    name: "/ (défaut)",
    value: "title",
  },
  {
    id: 1,
    class: "select-title",
    name: "Street Workout",
    value: "title",
  },
  {
    id: 2,
    class: "select-item",
    name: "Tuck",
    value: "Tuck",
  },
  {
    id: 3,
    class: "select-item",
    name: "Advanced tuck",
    value: "Advanced tuck",
  },
  {
    id: 4,
    class: "select-item",
    name: "Closed hip straddle",
    value: "Closed hip straddle",
  },
  {
    id: 5,
    class: "select-item",
    name: "One leg",
    value: "One leg",
  },
  {
    id: 6,
    class: "select-item",
    name: "Open hip straddle",
    value: "Open hip straddle",
  },
  {
    id: 7,
    class: "select-item",
    name: "Advanced on leg",
    value: "Advanced on leg",
  },
  {
    id: 8,
    class: "select-item",
    name: "Half lay",
    value: "Half lay",
  },
  {
    id: 9,
    class: "select-item",
    name: "One leg half",
    value: "One leg half",
  },
  {
    id: 10,
    class: "select-item",
    name: "Full",
    value: "Full",
  },
  {
    id: 11,
    class: "select-title",
    name: "General",
    value: "title",
  },
  {
    id: 11,
    class: "select-item",
    name: "A la Smith Machine",
    value: "A la Smith Machine",
  },
  {
    id: 11,
    class: "select-item",
    name: "A la machine",
    value: "A la machine",
  },
  {
    id: 11,
    class: "select-item",
    name: "A la chaise romaine",
    value: "A la chaise romaine",
  },
  {
    id: 11,
    class: "select-item",
    name: "A la poulie haute",
    value: "A la poulie haute",
  },
  {
    id: 11,
    class: "select-item",
    name: "A la poulie basse",
    value: "A la poulie basse",
  },
  {
    id: 11,
    class: "select-item",
    name: "Aux poulies hautes",
    value: "Aux poulies hautes",
  },
  {
    id: 11,
    class: "select-item",
    name: "Aux poulies basses",
    value: "Aux poulies basses",
  },
  {
    id: 11,
    class: "select-item",
    name: "Aux anneaux",
    value: "Aux anneaux",
  },
  {
    id: 12,
    class: "select-item",
    name: "Avec chaines",
    value: "Avec chaines",
  },
  {
    id: 13,
    class: "select-item",
    name: "Lean / penché ",
    value: "Lean",
  },
  {
    id: 13,
    class: "select-item",
    name: "Tiger",
    value: "Tiger",
  },
  {
    id: 13,
    class: "select-item",
    name: "Incliné",
    value: "Incliné",
  },
  {
    id: 14,
    class: "select-item",
    name: "Décliné",
    value: "Décliné",
  },
  {
    id: 14,
    class: "select-item",
    name: "Un pied / une main surrelevé(e)",
    value: "Un pied / une main surrelevé(e)",
  },
    {
    id: 11,
    class: "select-item",
    name: "Debout",
    value: "Debout",
  },
  {
    id: 11,
    class: "select-item",
    name: "Assis",
    value: "Assis",
  },
  {
    id: 11,
    class: "select-item",
    name: "Allongé",
    value: "Allongé",
  },
  {
    id: 11,
    class: "select-item",
    name: "A genoux",
    value: "A genoux",
  },
  {
    id: 11,
    class: "select-item",
    name: "Un genou et une main sur le banc",
    value: "Un genou et une main sur le banc",
  },
  {
    id: 11,
    class: "select-item",
    name: "Inversé",
    value: "Inversé",
  },
  {
    id: 11,
    class: "select-item",
    name: "Bras / jambes tendues",
    value: "Bras / jambes tendues",
  },
  {
    id: 14,
    class: "select-item",
    name: "Pieds / mains écartés",
    value: "Pieds / mains écartés",
  },
  {
    id: 14,
    class: "select-item",
    name: "Pieds / mains sérrés",
    value: "Pieds / mains serrés",
  },
  {
    id: 15,
    class: "select-item",
    name: "Unilatéral (à un bras / à une jambe)",
    value: "Unilatéral",
  },
  {
    id: 15,
    class: "select-item",
    name: "A un bras et à une jambe)",
    value: "A un bras et à une jambe)",
  },
  {
    id: 16,
    class: "select-item",
    name: "Archer (unilatéral assisté)",
    value: "Archer (unilatéral assisté)",
  },
  {
    id: 17,
    class: "select-item",
    name: "Sur les doigts",
    value: "Sur les doigts",
  },
    {
    id: 16,
    class: "select-item",
    name: "Sur la pointe des pieds",
    value: "Sur la pointe des pieds",
  },

  {
    id: 999,
    class: "select-title",
    name: "Elastiques ? => utiliser la catégorie dédiée",
    value: "title",
  },

];

export default variantes;
